image: node:10 #default node image

#stages
stages:
  - test
  - build


# demo_job_1:
#   stage: test
#   script:
#     - echo Hello World

test website:
  stage: test
  script:
    - npm install # install npm in docker image
    - npm run start &
    - sleep 15
    - curl "http://localhost:3000" | tac | tac| grep -q "React"