image: node:10 #default node image

#stages
stages:
  - build
  - test
  - deploy review
  - deploy staging

build website:
  stage: build
  script: 
    - npm install
    - npm install -g create-react-app
    - npm run build
  artifacts: 
      paths:
        - ./build

test artifact:
  image: alpine
  stage: test
  cache: {}
  script:
    - grep -q "Prominent Black Women" ./build/index.html

test website:
  stage: test
  script:
    - npm install # install npm in docker image
    - npm run start &
    - sleep 15
    - curl "http://localhost:3000" | tac | tac| grep -q "Prominent Black Women"
      
deploy review:
  stage: deploy review
  only:
    - merge_requests
  environment:
      name: review/$CI_COMMIT_REF_NAME
      url: https://greengreeniceisbetter-$CI_ENVIRONMENT_SLUG.surge.sh
  script:
    - npm install --global surge
    - surge --project ./public --domain greeniceisbetter-$CI_ENVIRONMENT_SLUG.surge.sh
      
# # deploy to heroku:
# #     state: deploy
# #     script: